// src/lib/components/cards/CardList.svelte
<script lang="ts">
  import Card from './Card.svelte'
  import type { CardData } from './types'

  interface Props {
    jsonData: CardData[]
    cardColor: string
    textColor: string
    selectedCard: CardData | null
    onSelectAnswer: (answer: string, card: CardData) => void
    onSelectCard: (card: CardData | null) => void
    displayAnswers: boolean
    resetCards: boolean
  }

  let {
    jsonData,
    cardColor,
    textColor,
    selectedCard,
    onSelectAnswer,
    onSelectCard,
    displayAnswers,
    resetCards
  }: Props = $props()
</script>

<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
  {#each jsonData as card, index}
    <Card
      {...card}
      {cardColor}
      {textColor}
      tabindex={index}
      displayAnswer={displayAnswers}
      resetCard={resetCards}
      onSelect={() => onSelectCard(card)}
      onSelectAnswer={(answer) => onSelectAnswer(answer, card)}
    />
  {/each}
</div>

// src/components/cards/CardList.tsx
'use client'
import React from 'react'
import Card from './Card'
import { type Card as CardInterface } from '@/components/cards/CardInterface'
import { motion } from 'framer-motion'
import './CardList.css'

interface CardListProps {
  cardColor: string
  textColor: string
  onSelectAnswer: (answer: string, card: CardInterface) => void
  onSelectCard: (card: CardInterface) => void
  jsonData: CardInterface[]
  selectedCard: CardInterface | null
  displayAnswers: boolean
  resetCards: boolean
}

const CardList: React.FC<CardListProps> = ({
  jsonData,
  cardColor,
  textColor,
  onSelectAnswer,
  onSelectCard,
  displayAnswers,
  resetCards,
}) => {
  const handleSelectCard = (card: CardInterface) => {
    onSelectCard(card)
  }

  const handleSelectAnswer = (answer: string, card: CardInterface) => {
    onSelectAnswer(answer, card)
  }

  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        delayChildren: 0.3,
        staggerChildren: 0.2,
      },
    },
  }

  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
    },
  }

  return (
    <div>
      <motion.div
        className="cards-container grid grid-cols-1 gap-2 md:grid-cols-2 md:gap-2 lg:grid-cols-2 lg:gap-2 xl:grid-cols-3 xl:gap-3 2xl:grid-cols-4 2xl:gap-3"
        variants={container}
        initial="hidden"
        animate="visible"
        style={{ gridAutoRows: '1fr' }}
      >
        {jsonData.map((card, index) => (
          <motion.div key={index} className="item" variants={item}>
            <Card
              key={index}
              {...card}
              cardColor={cardColor}
              textColor={textColor}
              onSelect={() => handleSelectCard(card)}
              onSelectAnswer={(answer) => handleSelectAnswer(answer, card)}
              tabIndex={index}
              displayAnswer={displayAnswers}
              resetCard={resetCards}
            />
          </motion.div>
        ))}
      </motion.div>
    </div>
  )
}

export default CardList
