// src/components/buttons/PrimaryButton.tsx
import React from 'react'

interface PrimaryButtonProps {
  children: React.ReactNode
  onClick: () => void
  highlight?: boolean
  disabled?: boolean
  tabIndex?: number
}

const PrimaryButton = ({
  onClick,
  children,
  highlight = false,
  disabled = false,
  tabIndex = 0,
}: PrimaryButtonProps) => {
  return (
    <>
      <button
        type="button"
        className={`${highlight ? 'bg-indigo-500' : 'bg-slate-900'} 
          ${disabled ? 'cursor-not-allowed bg-indigo-400' : ''}
          border-2 border-indigo-500 rounded-md active:border-slate-900  
          px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 
          focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500`}
        onClick={onClick}
      >
        {children}
      </button>
    </>
  )
}

export default PrimaryButton

// src/lib/components/buttons/PrimaryButton.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface Props {
    onclick: () => void
    tabindex?: number
    disabled?: boolean
    highlight?: boolean
    children: Snippet
  }

  let { onclick, tabindex = 0, disabled = false, highlight = false, children }: Props = $props()
</script>

<button
  type="button"
  {tabindex}
  {disabled}
  class="rounded-md px-3 py-2 text-sm font-semibold shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 {highlight
    ? 'bg-indigo-600 text-white hover:bg-indigo-500 focus-visible:outline-indigo-600'
    : 'bg-slate-500 text-white hover:bg-slate-400'} disabled:opacity-50 disabled:cursor-not-allowed"
  {onclick}
>
  {@render children()}
</button>
